---
output: pdf_document
geometry: margin=0in

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE, dev = 'cairo_pdf')
```

```{r FigA, echo=FALSE, message=FALSE, fig.width=(3*(2.0694+0.025)), fig.height=2*(1.1837+0.025), fig.align='left'}
source("../../../Paper/Helper_functions/image_panel.R")

FigA = image_panel(path = "D:/R_projects/Developmental-Landscape/Paper/Figures/Figure_1/Control.Rps19b-GFP.40x.4_s3_5.tif", 
            colors_to_return = c("red", "blue"), 
            genotype_annotation = "RpS19b::GFP",
            red_annotation = "1B1", blue_annotation = "Vasa ",
            label_letters = c("A", "A'", "A''"))

FigB = image_panel(path = "D:/R_projects/Developmental-Landscape/Paper/Figures/Figure_1/Control.Rps19b-GFP.40x.4_s3_5.tif", 
            colors_to_return = c("red", "green"), 
            genotype_annotation = "RpS19b::GFP",
            red_annotation = "1B1", blue_annotation = "Vasa ",
            label_letters = c("B", "B'", "B''"))

Figure1 = multi_panel_figure(
    width = c(3*(2.0694+0.025)),
    height = c(2*(1.1837+0.025)), columns = 1, rows = 2, row_spacing = 0.025, column_spacing = 0, unit = "in")

Figure1 = Figure1 %>% 
  fill_panel(FigA, label = "", scaling = "none", panel_clip = "on") %>%
  fill_panel(FigB, label = "", scaling = "none", panel_clip = "on")
Figure1

# ggsave(filename = "FigA.pdf", FigA, width = 2*(3*(2.0694+0.026)), height = (1.1596+0.026))
```